//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        public int Id { get; set; }
        [Display(Name = "Evening Showtime")]
        public System.DateTime Date { get; set; }
        public string LetterStatus { get; set; }
        public string ReferenceNo { get; set; }
        public string Responsible { get; set; }
        public string Assign { get; set; }
        public string Comments { get; set; }
    }
}
