//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        public int Id { get; set; }
        public string Sender { get; set; }
        public string Responsible { get; set; }
        public string Subject { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> LetterDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string Type { get; set; }
        public string StatusOfLetter { get; set; }
        public string ScannedImage { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> LetterStatusId { get; set; }
        public Nullable<int> LetterTypeId { get; set; }
        public Nullable<int> LetterFromId { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual LetterFrom LetterFrom { get; set; }
        public virtual LetterStatu LetterStatu { get; set; }
        public virtual LetterType LetterType { get; set; }
    }
}
