//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Letter
    {
        public int Id { get; set; }
        public string LetterFrom { get; set; }
        public string Responsible { get; set; }
        public string Subject { get; set; }
        public string ReferenceNo { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:hh:mm tt}", ApplyFormatInEditMode = true)]
        [Display(Name = "Evening Showtime")]
        public System.DateTime LetterDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:hh:mm tt}", ApplyFormatInEditMode = true)]
        [Display(Name = "Evening Showtime")]
        public System.DateTime ReceiveDate { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string BranchName { get; set; }
        public string LetterType { get; set; }
        public string LetterStatus { get; set; }
        public string ScannedImage { get; set; }
    }
}
