//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LetterManagementDBEntities : DbContext
    {
        public LetterManagementDBEntities()
            : base("name=LetterManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<SenderType> SenderTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<LetterStatu> LetterStatus { get; set; }
        public virtual DbSet<LetterType> LetterTypes { get; set; }
        public virtual DbSet<LetterFrom> LetterFroms { get; set; }
        public virtual DbSet<Letter> Letters { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
    }
}
