//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterManagementSystem.Context
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    public partial class Letter
    {
        public int Id { get; set; }
        public int SenderId { get; set; }
        public int RecipientId { get; set; }
        public string Subject { get; set; }
        public string ReferenceNo { get; set; }
        public System.DateTime LetterDate { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public int BranchId { get; set; }
        public string LetterType { get; set; }
        public int LetterStatusId { get; set; }
        public string ScannedImage { get; set; }
        public  HttpPostedFileBase ImageFile { get; set; }
    }
}
