//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VisitDetail
    {
        public int Id { get; set; }
      //  [Required(ErrorMessage ="(Field is Rquried)")]
        public Nullable<System.DateTime> DateOfVisit { get; set; }
        public Nullable<System.DateTime> NextVistDate { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
        public string VisitType { get; set; }
        public string Lead_Conversion { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
        public string DuscussedProduct { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
        public string DepositeAmount { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
        public string Comments { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
        public string TypeOfClient { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
        public string BusinessType { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
        public string ClientsName { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
        public string ClientsOrganization { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
        public string ConcernedPerson { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
        public string ClientsDesignation { get; set; }
        public string TelephoneNo { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
       //[MinLength(11,ErrorMessage ="Mobile num length should be 11")]
        public string MobileNo { get; set; }
       //  [Required(ErrorMessage ="(Field is Rquried)")]
        public string Address { get; set; }
    }
}
